### ISSUE TITLE
4d (multiple frequencies) reshape issue in DatasetEphy

### ISSUE THREAD

**Issue by StanSStanman** [brainets/frites#12]
Hello @EtienneCmb ,
when 4d arrays are used in DatasetEphy as x (analysis on multiples frequency bands), the reshape in 3d form does not take in consideration the single subject's number of epochs. 
Here the code I'm referring at:
in [**frites/dataset/ds_ephy.py**](https://github.com/brainets/frites/blob/0c8744cf3dfce8644fa8261a759978510cbf8c35/frites/dataset/ds_ephy.py#L137) in line 142

```
n_e, n_r, n_f, n_t = x[0].shape
for k in range(len(x)):
    x[k] = x[k].reshape(n_e, n_r, n_f * n_t)
```

Thank you so much BG! :kissing_heart:

**Comment by EtienneCmb** [comment]
Hello @StanSStanman !

Thanks for pointing me out the issue. Probably the best way to fix it would be that the `self._reshape` becomes a **list of shapes** instead of just the shape of the first element. Something like :

In [ds_ephy](https://github.com/brainets/frites/blob/master/frites/dataset/ds_ephy.py#L139) :

```python
self._reshape = None
if all([k.ndim == 4 for k in x]):
    logger.debug(f"    4d reshaping")
    self._reshape = []
    for k in range(len(x)):
        n_e, n_r, n_f, n_t = x[k].shape
        x[k] = x[k].reshape(n_e, n_r, n_f * n_t)
        self._reshape.append((n_f, n_t))
```

Then, you also need to modify the [WfMi](https://github.com/brainets/frites/blob/master/frites/workflow/wf_mi.py#L263) with something like :

```python
self._reshape = dataset._reshape
if isinstance(self._reshape, list):
    logger.debug(f"    reshaping before computing statistics")
    for k in range(len(mi)):
        n_f, n_t = self._reshape[k]
        n_p, n_s, _ = mi_p[k].shape
        mi[k] = mi[k].reshape(n_s, n_f, n_t)
        mi_p[k] = mi_p[k].reshape(n_p, n_s, n_f, n_t)
```

If you want to test your code, there's one example illustrating spatio-temporal clusters ([online doc](https://brainets.github.io/frites/auto_examples/mi/plot_mi_time_frequency.html#sphx-glr-auto-examples-mi-plot-mi-time-frequency-py) and [github code](https://github.com/brainets/frites/blob/master/examples/mi/plot_mi_time_frequency.py)).

I suggest that you modify this example such that each simulated subject has a different number of trials. Then you can start to modify the scripts and submit the PR.

What do you think?

**Comment by StanSStanman** [comment]
Hello @EtienneCmb 

Thanks for your answer.  As we discussed trough other channels, I'm going to fix the bug, but without transforming `shape._reshape` in a list of tuples. 
Indeed this attribute is in the form of (n_freqs, n_times) and those two dimensions should remains the same across all the subjects. 

I will also update the example code, to include the case of computing mi across subjects with a variable number of trials.

See you soon!
